### ISSUE TITLE
Creation of the OpenCTI app

### ISSUE THREAD

**Issue by SamuelHassine** [Shuffle/python-apps#1]
Hello,

It could be great to have [OpenCTI](https://www.opencti.io) in the available apps! 

Thanks!

Kind regards,
Samuel

**Comment by frikky** [comment]
Hey, does OpenCTI have an OpenAPI specification or similar?

I think that's the right way to go for this.

**Comment by frikky** [comment]
@SamuelHassine I've done some work to check OpenCTI and saw that it uses GraphQL. Would you be open to a chat about how this could be implemented well? I haven't done much work with GraphQL, but would like to automate at least parts of it.

If the API was smaller, I'd just type it up, but since it's quite extensive, that could take a while.

**Comment by frikky** [comment]
This is now available: https://shuffler.io/apps/24555182e0063c1800d0c8e320e0892a
